account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('signup', views.signup, name='signup'),
    path('home', views.home, name='home'),
    path('structure', views.structure, name='structure'),
    path('invited', views.invited, name='invited'),
    path('invited_ajax', views.invited_ajax, name='invited_ajax'),
    path('bonus_history', views.bonus_history, name='bonus_history'),
    path('validate_username_ajax', views.validate_username_ajax, name='validate_username_ajax'),
    path('documentation', views.documentation, name='documentation'),
    path('notifications', views.notifications, name='notifications'),
]

aroma/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_title = ''
admin.site.site_header = 'Администрирование'
admin.site.index_title = ''

urlpatterns = [
    path('',include('main.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('graph/', include('graph.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/',include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', CartDetail, name='CartDetail'),
    path('add/<int:product_id>', CartAdd, name='CartAdd'),
    path('remove/<int:product_id>', CartRemove, name='CartRemove')
]

graph/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from graph.views import ModelListGraphsView, ModelGraphView, ModelGraphInlineView

app_name = 'graph'

urlpatterns = [
    url(r'^(?P<modpath>[-._\w]+)/(?P<pk>[0-9]+)/$', ModelGraphInlineView.as_view(), name="mpttgraph-inline"),
    url(r'^(?P<modpath>[-._\w]+)/(?P<pk>[0-9]+)/$', ModelGraphView.as_view(), name="mpttgraph-detail"),
    url(r'^', ModelListGraphsView.as_view(), name="mpttgraph-index"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('CartDetail')


def CartDetail(request):
    # cart = Cart(request)
    # return render(request, 'cart/detail.html', {'cart': cart})
    user = request.user
    node = user.node
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    return render(request, 'cart/detail.html', {'cart': cart, 'node': node})
# Create your views here.

cart/templates/cart/detail.html
{% extends "base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block navbar %}
    	<nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#"></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">

                        {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                <li>
                                <a href="{% url 'CartDetail' %}">
								 <i class="ti-shopping-cart-full"></i>
								 <p>{{ total_items }} тов. {{ cart.get_total_price }} y.e.</p>
                               </a>
                               </li>
                                {% else %}
                                <li>
                                <a href="#">
								 <i class="ti-shopping-cart"></i>
								 <p>Корзина пустая</p>
                               </a>
                               </li>
                            {% endif %}
                        {% endwith %}
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-user"></i>
									<p></p>
									<b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'account:user_logout' %}">Выйти</a></li>
                              </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
{% endblock %}
{% block sidebar %}
	<div class="sidebar" data-background-color="white" data-active-color="danger">
    <!--
		Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
		Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
	-->
    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="" class="simple-text">
                    Elite Travel Club
                </a>
            </div>
            <ul class="nav">
                <li>
                    <a href="{% url 'account:home' %}">
                        <i class="ti-home"></i>
                        <p>Общая сводка</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'graph:mpttgraph-inline' 'account.models.Node'  node.id %}">
                        <i class="ti-view-list-alt"></i>
                        <p>Структура</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:invited' %}">
                        <i class="ti-user"></i>
                        <p>Приглашенные</p>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'ProductList' %}">
                        <i class="ti-home"></i>
                        <p>Интернет магазин</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:documentation' %}">
                        <i class="ti-map"></i>
                        <p>Документация</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:notifications' %}">
                        <i class="ti-bell"></i>
                        <p>Уведомления</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>
{% endblock %}
{% block content %}
    <div class="content">
            <div class="container-fluid">
                <div class="row">
                      <section id="content row" class="container-fluid">
            <div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4>Ваша корзина товаров</h4>
        </div>
        <div class="content table-responsive table-full-width">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{% url 'ProductDetail' product.id %}">
                <img src="{{ product.image.url }}" width="100" height="100" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url 'CartAdd' product.id %}" method="post" class="add">
                    <!--{{ item.quantity }}-->
    {{ item.update_quantity_form.quantity }}
    {{ item.update_quantity_form.update }}
    {% csrf_token %}
    <input type="submit" value="Обновить">
</form>
            </td>
            <td><a href="remove/{{product.id}}" class="text-danger">Удалить</a></td>
            <td class="num">{{ item.price }} y.e.</td>
            <td class="num">{{ item.total_price }} y.e.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Общее</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} y.e.</td>
        </tr>
    </tbody>
  </table>
        </div>
    </div>
</div>
  <p class="text-right">
    <a href="{% url 'ProductList' %}" class="btn btn-info btn-fill">Продолжить Шопинг</a>
    <a href="{% url 'OrderCreate' %}" class="btn btn-info btn-fill">Оформить заказ</a>
  </p>
                      </section>
                </div>
            </div>
        </div>




{% endblock %}